parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: ./
  ecmaVersion: 2019
  ecmaFeatures:
    jsx: true

settings:
  import/core-modules:
    - "@expo/vector-icons"
    - "@expo/websql"
  react:
    version: detect

plugins:
  - "@typescript-eslint/eslint-plugin"
  - "prettier"
  - "react"
  - "jest"

extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
  - "plugin:jest/recommended"
  - "plugin:jest/style"

env:
  browser: true
  node: true

overrides:
  # Allow console in tests
  - files: "**/*.test.js"
    rules:
      no-console: off

rules:
  jest/no-disabled-tests: error
  prettier/prettier: error

  # useless
  class-methods-use-this: off
  import/no-unresolved: off # webpack paths (./image?resize) break this
  lines-between-class-members: off
  no-restricted-syntax: [off, "BinaryExpression[operator='in']"]
  no-return-assign: [error, except-parens]
  no-underscore-dangle: off
  no-unused-vars: [error, { argsIgnorePattern: "^_" }]
  react/jsx-closing-tag-location: off
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
  react/jsx-wrap-multilines: off
  react/no-multi-comp: off
  react/react-in-jsx-scope: off
  "@typescript-eslint/no-parameter-properties": off

  # possibly useful, but annoying
  jsx-a11y/alt-text: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-static-element-interactions: off
  react/forbid-prop-types: off
  react/no-danger: off
  react/no-unescaped-entities: off
  "@typescript-eslint/explicit-member-accessibility": off
  "@typescript-eslint/explicit-function-return-type": off

  # turn these on later, when we have time to clear the errors
  react/prop-types: off

  # conflicting stuff from typescript lint
  "@typescript-eslint/indent": off
