dist: xenial

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - ${HOME}/.cache/yarn

before_install:
  - "echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf &&
    sudo sysctl -p"

install:
  - yarn install --dev --frozen-lockfile

script: ./scripts/ci.sh

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: master
