dist: xenial

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - ${HOME}/.cache/yarn

install:
  - yarn install --dev --frozen-lockfile

script:
  - yarn format:check
  - yarn test:ci
