dist: xenial

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - ${HOME}/.cache/yarn

install:
  - yarn install --dev --frozen-lockfile

script: ./scripts/ci.sh

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: master
