import Procedure from "./Procedure";
import { Asset } from "expo";
import * as Recipes from "../data/recipes";

// Recipe represents something the user can make.
// We should take photos of all of these, and include them.

export default interface Recipe {
  // Requirements for the recipe. Generated by passing in the configuration.
  requires: (config: { [key: string]: any }) => Procedure[];

  // Default configuration for the recipe.
  defaults: { [key: string]: any };

  // Name/body to show in the UI.
  name: string;
  body?: string;

  // List of photos of this Recipe, when it's cooked.
  images: Asset[];
}

// Serializable description of a recipe (with configuration)
// usable in routing/persistence/etc.
export interface RecipeSpec {
  // name of the recipe in the exported `Recipes` map
  id: string;

  // That recipe's configuration. Used to generate the initial dependencies.
  config: { [key: string]: any };
}

// export recipe list from /data/recipes
export { Recipes };
